[project]
name = "asyncIO_Project"
version = "0.1.0"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.11.18",
    "aiosqlite>=0.21.0",
    "flask>=3.1.1",
    "httpx>=0.28.1",
    "requests==2.31.0",
]

[tool.uv]

